version: '2'

services:
  akaunting-db:
    restart: always
    image: mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD= '1'
      - MYSQL_PASSWORD=akauntingdbpassword
      - MYSQL_DATABASE=akaunting
      - MYSQL_USER=akaunting
    volumes:
      - /srv/docker/akaunting/mysql:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: "/usr/bin/mysql --user=akaunting --password=akauntingdbpassword --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 30s
      retries: 15

  akaunting-app:
    restart: always
    image: timeens/akaunting-reverse-proxy:latest
    command: app:akaunting
    environment:
    - DEBUG=false
    - TZ=Europe/Berlin
    - DB_HOST=akaunting-db
    - DB_USER=akaunting
    - DB_PASS=akauntingdbpassword
    - DB_NAME=akaunting
    - AKAUNTING_URL=https://accounting.example.org
    - AKAUNTING_COMPANY_NAME=Example Inc
    - AKAUNTING_COMPANY_EMAIL=contact@example.org
    - AKAUNTING_ADMIN_EMAIL=contact@exampleinc.org
    - AKAUNTING_ADMIN_PASSWORD=akauntingadminpassword
    - AKAUNTING_BACKUPS_EXPIRY=0
    depends_on:
      akaunting-db:
        condition: service_healthy
    networks:
      - default
    volumes:
    - /srv/docker/akaunting/akaunting:/var/lib/akaunting

  akaunting-web:
    restart: always
    image: timeens/akaunting-reverse-proxy:latest
    command: app:nginx
    environment:
    - AKAUNTING_PHP_FPM_HOST=akaunting-app
    - AKAUNTING_PHP_FPM_PORT=9000
    depends_on:
      - akaunting-app
    ports:
      - "80:80"
    # comment the ports section when using traefik
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.akaunting-app.entrypoints=http"
    #  - "traefik.http.routers.akaunting-app.rule=Host(`accounting.example.org`)"
    #  - "traefik.http.middlewares.akaunting-app-https-redirect.redirectscheme.scheme=https"
    #  - "traefik.http.routers.akaunting-app.middlewares=akaunting-app-https-redirect"
    #  - "traefik.http.routers.akaunting-app-secure.entrypoints=https"
    #  - "traefik.http.routers.akaunting-app-secure.rule=Host(`accounting.example.org`)"
    #  - "traefik.http.routers.akaunting-app-secure.tls=true"
    #  - "traefik.http.routers.akaunting-app-secure.service=akaunting-app"
    #  - "traefik.http.services.akaunting-app.loadbalancer.server.port=80"
    #  - "traefik.docker.network=proxy"
    networks:
      - default
    #  - proxy

#networks:
  #proxy:
    #external: true
